export const SKILL_LIST = [
  "python", "sql", "azure", "aws", "java", "react", "etl", "spark",
  "javascript", "typescript", "node", "nodejs", "docker", "kubernetes", "html",
  "css", "mongodb", "postgresql", "mysql", "git", "linux", "c++", "c#", "ruby",
  "php", "swift", "kotlin", "flutter", "django", "flask", "fastapi",
  "tensorflow", "pytorch", "machine learning", "deep learning", "nlp",
  "tableau", "power bi", "excel", "angular", "vue", "nextjs", "express",
  "graphql", "rest api", "redis", "kafka", "hadoop", "airflow", "snowflake",
  "databricks", "gcp", "terraform", "jenkins", "ci/cd", "agile", "scrum",
  "jira", "figma", "sketch", "photoshop", "illustrator", "sass", "tailwind",
  "bootstrap", "material ui", "redux", "zustand", "webpack", "vite",
  "spring boot", "hibernate", ".net", "go", "golang", "rust", "scala",
  "r", "matlab", "sas", "spss", "pandas", "numpy", "scikit-learn",
  "opencv", "computer vision", "natural language processing", "bert", "gpt",
  "llm", "langchain", "rag", "vector database", "pinecone", "chromadb",
  "selenium", "cypress", "jest", "mocha", "pytest", "unittest",
  "microservices", "serverless", "lambda", "s3", "ec2", "rds",
  "dynamodb", "firebase", "supabase", "vercel", "netlify", "heroku",
  "digital ocean", "nginx", "apache", "load balancing", "caching",
  "oauth", "jwt", "authentication", "authorization", "security",
  "blockchain", "solidity", "web3", "ethereum", "smart contracts",
  "ios", "android", "react native", "xamarin", "unity", "unreal",
  "three.js", "d3.js", "chart.js", "matplotlib", "seaborn", "plotly",
  "power automate", "sharepoint", "salesforce", "sap", "oracle",
  "data warehouse", "data lake", "data pipeline", "data modeling",
  "business intelligence", "data analytics", "data science",
  "statistics", "probability", "linear algebra", "calculus",
  "azure data factory", "azure synapse", "azure devops", "azure functions",
  "aws glue", "aws redshift", "aws emr", "aws sagemaker",
  "google bigquery", "google cloud", "looker", "dbt",
  "informatica", "talend", "ssis", "ssrs", "ssas",
  "pyspark", "hive", "presto", "athena", "cosmos db",
  "neo4j", "cassandra", "elasticsearch", "kibana", "grafana",
  "splunk", "datadog", "new relic", "prometheus",
  "ansible", "puppet", "chef", "vagrant", "packer",
  "istio", "helm", "argocd", "tekton", "gitlab ci",
  "github actions", "circleci", "travis ci", "bamboo",
  "confluence", "trello", "asana", "monday", "notion",
  "soap", "xml", "json", "yaml", "protobuf", "grpc",
  "rabbitmq", "activemq", "celery", "sidekiq",
  "stripe", "twilio", "sendgrid", "auth0", "okta",
  "adobe xd", "invision", "zeplin",
  "rollup", "parcel", "esbuild", "turbopack",
  "storybook", "chromatic", "percy", "playwright", "puppeteer",
  "gatling", "jmeter", "locust", "k6",
  "sonarqube", "fortify", "checkmarx", "snyk", "veracode",
];
